### ISSUE TITLE
NO IO Factories

### ISSUE THREAD

**Issue by pst2154** [ptyap/MATLAB-ITK-IO#1]
Hi, I was testing this out and I built it and then tried to read an image

There are no registered IO factories.
  Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.

**Comment by ptyap** [comment]
Hi pst2154, one possible cause is that ITK does not recognize the format of the file you are trying to read. Could you let me know the format? Thanks!

**Comment by pst2154** [comment]
I have tried tif, jpg, dcm. Maybe its because its windows and I used static libraries? I build with mex command and not Cmake, I am on windows, built the VTK libraries, used static ones and included them all

mex -v -I'C:\Program Files\ITK\include\ITK-4.7' -I'C:\MATLAB-ITK-IO\Source' -L'C:\Program Files\ITK\lib' -l'ITKBiasCorrection-4.7'  -l'ITKBioCell-4.7'  -l'ITKCommon-4.7'   -l'ITKDICOMParser-4.7'  -l'ITKEXPAT-4.7'    -l'ITKFEM-4.7'  -l'ITKIOBMP-4.7'    -l'ITKIOBioRad-4.7' -l'ITKIOCSV-4.7'    -l'ITKIOGDCM-4.7'   -l'ITKIOGE-4.7' -l'ITKIOGIPL-4.7'   -l'ITKIOHDF5-4.7'   -l'ITKIOIPL-4.7'    -l'ITKIOImageBase-4.7'  -l'ITKIOJPEG-4.7'   -l'ITKIOLSM-4.7'    -l'ITKIOMRC-4.7'    -l'ITKIOMesh-4.7'   -l'ITKIOMeta-4.7'   -l'ITKIONIFTI-4.7'  -l'ITKIONRRD-4.7'   -l'ITKIOPNG-4.7'    -l'ITKIOSiemens-4.7'    -l'ITKIOSpatialObjects-4.7' -l'ITKIOStimulate-4.7'  -l'ITKIOTIFF-4.7'   -l'ITKIOTransformBase-4.7'  -l'ITKIOTransformHDF5-4.7'  -l'ITKIOTransformInsightLegacy-4.7' -l'ITKIOTransformMatlab-4.7'    -l'ITKIOVTK-4.7'    -l'ITKIOXML-4.7'    -l'ITKKLMRegionGrowing-4.7' -l'ITKLabelMap-4.7' -l'ITKMesh-4.7' -l'ITKMetaIO-4.7'   -l'ITKNrrdIO-4.7'   -l'ITKOptimizers-4.7'   -l'ITKOptimizersv4-4.7' -l'ITKPath-4.7' -l'ITKPolynomials-4.7'  -l'ITKQuadEdgeMesh-4.7' -l'ITKSpatialObjects-4.7'   -l'ITKStatistics-4.7'   -l'ITKVNLInstantiation-4.7' -l'ITKVTK-4.7'  -l'ITKVideoCore-4.7'    -l'ITKVideoIO-4.7'  -l'ITKWatersheds-4.7'   -l'ITKgiftiio-4.7'  -l'ITKniftiio-4.7'  -l'ITKznz-4.7'  -l'itkNetlibSlatec-4.7' -l'itkdouble-conversion-4.7'    -l'itkgdcmCommon-4.7'   -l'itkgdcmDICT-4.7' -l'itkgdcmDSED-4.7' -l'itkgdcmIOD-4.7'  -l'itkgdcmMSFF-4.7' -l'itkgdcmjpeg12-4.7'   -l'itkgdcmjpeg16-4.7'   -l'itkgdcmjpeg8-4.7'    -l'itkhdf5-4.7' -l'itkhdf5_cpp-4.7' -l'itkjpeg-4.7' -l'itkopenjpeg-4.7' -l'itkpng-4.7'  -l'itksys-4.7'  -l'itktiff-4.7' -l'itkv3p_lsqr-4.7' -l'itkv3p_netlib-4.7'   -l'itkvcl-4.7'  -l'itkvnl-4.7'  -l'itkvnl_algo-4.7' -l'itkzlib-4.7' itkRead.cxx

> > a=itkRead('pic.jpg')
> > Error using itkRead
> > c:\program files\itk\include\itk-4.7\itkImageFileReader.hxx:143:
> >  Could not create IO object for reading file pic.jpg
> >   There are no registered IO factories.
> >   Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.
> > a=itkRead('img1.tif')
> > Error using itkRead
> > c:\program files\itk\include\itk-4.7\itkImageFileReader.hxx:143:
> >  Could not create IO object for reading file img1.tif
> >   There are no registered IO factories.
> >   Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.

**Comment by ptyap** [comment]
I think it is best to use MATLAB's 'imread' to read jpeg and tif images and 'dicomread' to read dcm images. itkRead can be used to read Analyze, NIFTI, MetaImage, and NRRD images.

**Comment by pst2154** [comment]
I do get the same error with those though.

a=itkRead('CorpusCallosumMeanShape.mha')
Error using itkRead
c:\program files\itk\include\itk-4.7\itkImageFileReader.hxx:143:
 Could not create IO object for reading file CorpusCallosumMeanShape.mha
  There are no registered IO factories.
  Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.

a=itkRead('avg152T1_LR_nifti.nii')
Error using itkRead
c:\program files\itk\include\itk-4.7\itkImageFileReader.hxx:143:
 Could not create IO object for reading file avg152T1_LR_nifti.nii
  There are no registered IO factories.
  Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.

a=itkRead('BrainProtonDensitySliceBorder20.raw')
Error using itkRead
c:\program files\itk\include\itk-4.7\itkImageFileReader.hxx:143:
 Could not create IO object for reading file BrainProtonDensitySliceBorder20.raw
  There are no registered IO factories.
  Please visit http://www.itk.org/Wiki/ITK/FAQ#NoFactoryException to diagnose the problem.

**Comment by ptyap** [comment]
Hmm...This is strange. Let me check my Windows compiled binaries and get back to you on this. I remember compiling in Windows being quite tricky.

BTW, can you try dynamically linked libraries?

Which version of Windows are you using?

**Comment by pst2154** [comment]
windows 7, latest VTK version

I will have to build the VTK shared libs, takes a while

**Comment by pst2154** [comment]
Update: I built it with the Cmakelist and then included ITKIOGDCM and it worked perfectly for a dcm image, thanks!

**Comment by ptyap** [comment]
Awesome! Good to know it works for dcm as well. Thanks!
